# External gems
gems:
  # - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude: ["/vendor/", "/bower_components/"]

# Site settings
title: Amphibian Disease Portal
subtitle: "A repository for aggregating information on Bd and Bsal"
email: amphibiaweb@berkeley.edu
name: AmphibiaWeb
description: >
  A repository for aggregating information on Bd and Bsal
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://updates.amphibiandisease.org" # the base hostname & protocol for your site
cover: "assets/Ensatina_closeup_Yap_1024.jpg"
logo: "assets/logo.jpg"

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
 #ga_tracking_id: "UA-69012106-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Portal
    desc: "Information on the Amphibian Disease portal"

  - cat: News
    desc: "Latest publications, media and news on Bsal"

  - cat: Resources
    desc: "Resources on amphibian diseases"
 

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
   - name: Twitter
     icon: twitter
     username: AmphibiaWeb
     url: https://twitter.com/AmphibiaWeb
     desc: Follow me on Twitter
     share: true

   - name: Facebook
     icon: facebook
     username: AmphibiaWeb
     url: https://www.facebook.com/AmphibiaWeb
     desc: Friend me on Facebook
     share: true

   - name: GitHub
     icon: github
     username: AmphibiaWeb
     url: https://github.com/AmphibiaWeb/amphibian-disease-tracker
     desc: Contribute on GitHub
     share: true

  # - name: LinkedIn
  #   icon: linkedin
  #   username: Ben Centra
  #   url: https://www.linkedin.com/pub/ben-centra/47/769/60a
  #   desc: Connect with me on LinkedIn
  #   share: true

  # - name: Google+
  #   icon: google-plus
  #   username:
  #   url:
  #   desc: Add me to your Circles
  #   share: true

  # - name: YouTube
  #   icon: youtube
  #   username:
  #   url:
  #   desc: Subscribe on YouTube
  #   share: false

  # - name: Instagram
  #   icon: instagram
  #   username:
  #   url:
  #   desc: Follow me on Instagram
  #   share: false

  # - name: Pinterest
  #   icon: pinterest
  #   username:
  #   url:
  #   desc: Follow me on Pinterest
  #   share: true

  # - name: SoundCloud
  #   icon: soundcloud
  #   username:
  #   url:
  #   desc: Follow me on SoundCloud
  #   share: false

  # - name: Tumblr
  #   icon: tumblr
  #   username:
  #   url:
  #   desc: Follow me on Tumblr
  #   share: false

  # - name: Vimeo
  #   icon: vimeo-square
  #   username:
  #   url:
  #   desc: Follow me on Vimeo
  #   share: false

  # - name: Vine
  #   icon: vine
  #   username:
  #   url:
  #   desc: Follow me on Vine
  #   share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
